-- =============================================================
-- NDIS Ready — Supabase Schema
-- Run this in Supabase SQL Editor (Dashboard → SQL Editor → New query)
-- =============================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================
-- ORDERS — one row per Stripe payment
-- =============================================================
CREATE TABLE IF NOT EXISTS orders (
  id                      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  stripe_session_id       TEXT UNIQUE,
  stripe_payment_intent   TEXT,
  stripe_subscription_id  TEXT,
  email                   TEXT NOT NULL,
  name                    TEXT,
  amount_cents            INTEGER,
  product_tier            TEXT CHECK (product_tier IN ('free_sample', 'registration_kit', 'value_bundle', 'stay_ready')),
  status                  TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'refunded', 'canceled', 'failed')),
  paid_at                 TIMESTAMPTZ,
  refunded_at             TIMESTAMPTZ,
  canceled_at             TIMESTAMPTZ,
  created_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS orders_email_idx ON orders(email);
CREATE INDEX IF NOT EXISTS orders_stripe_session_idx ON orders(stripe_session_id);
CREATE INDEX IF NOT EXISTS orders_status_idx ON orders(status);

-- =============================================================
-- DOCUMENT ACCESS — tracks what each customer can download
-- =============================================================
CREATE TABLE IF NOT EXISTS document_access (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_id        UUID REFERENCES orders(id) ON DELETE SET NULL,
  email           TEXT NOT NULL,
  product_tier    TEXT,
  access_token    TEXT UNIQUE NOT NULL,
  variables       JSONB,          -- personalisation variables generated by OpenAI
  doc_count       INTEGER DEFAULT 65,
  download_count  INTEGER DEFAULT 0,
  expires_at      TIMESTAMPTZ NOT NULL,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS doc_access_token_idx ON document_access(access_token);
CREATE INDEX IF NOT EXISTS doc_access_email_idx ON document_access(email);

-- =============================================================
-- DOCUMENT DOWNLOADS — audit log of every download
-- =============================================================
CREATE TABLE IF NOT EXISTS document_downloads (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  access_id     UUID REFERENCES document_access(id) ON DELETE CASCADE,
  email         TEXT NOT NULL,
  document_id   TEXT NOT NULL,   -- e.g. '49'
  document_name TEXT,
  downloaded_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS doc_downloads_email_idx ON document_downloads(email);

-- =============================================================
-- WEBHOOK LOG — audit trail of all Stripe events
-- =============================================================
CREATE TABLE IF NOT EXISTS webhook_log (
  id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  event_type   TEXT NOT NULL,
  stripe_id    TEXT,
  email        TEXT,
  metadata     JSONB,
  received_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS webhook_log_type_idx ON webhook_log(event_type);
CREATE INDEX IF NOT EXISTS webhook_log_received_idx ON webhook_log(received_at DESC);

-- =============================================================
-- ROW LEVEL SECURITY
-- Service key (used in API) bypasses RLS
-- Anon key (used in frontend) is locked down
-- =============================================================
ALTER TABLE orders            ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_access   ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_downloads ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_log       ENABLE ROW LEVEL SECURITY;

-- No public access — all reads/writes go through service key in API functions
-- (frontend never touches these tables directly)
