-- =============================================================
-- NDIS Ready — Supabase Storage Setup
-- Run AFTER schema.sql in Supabase SQL Editor
-- =============================================================

-- Create 'templates' bucket — stores the 65 master .docx files
-- Private: only accessible via signed URLs generated by the API
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'templates',
  'templates',
  false,
  52428800, -- 50MB limit per file
  ARRAY['application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/msword']
)
ON CONFLICT (id) DO NOTHING;

-- Create 'customer-docs' bucket — stores future AI-generated personalised docs
-- Private: customer-specific signed URLs only
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'customer-docs',
  'customer-docs',
  false,
  52428800,
  ARRAY['application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/msword', 'application/zip']
)
ON CONFLICT (id) DO NOTHING;

-- Storage RLS: only service role can read/write
-- (API uses service key, so it bypasses these policies)
CREATE POLICY "Service role only — templates"
  ON storage.objects FOR ALL
  USING (bucket_id = 'templates' AND auth.role() = 'service_role');

CREATE POLICY "Service role only — customer-docs"
  ON storage.objects FOR ALL
  USING (bucket_id = 'customer-docs' AND auth.role() = 'service_role');
